name: Autograding Tests
'on':
- pull_request
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    # Was used when developing repo
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.0"
    - name: Install dependendies, setup
      run: pip install .; chmod +x collect_files.sh
    - name: Download tests script
      env:
        tests_url: ${{ secrets.TESTS_URL }}
      run: mkdir tests; curl -o tests/test_collect_files.py "$tests_url"
    - name: Task 1
      id: task-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Task 1
        command: pytest tests/test_collect_files.py::test_script_runs_and_accepts_two_args --tb=line
        timeout: 10
        max-score: 1
    - name: Task 2
      id: task-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Task 2
        command: pytest tests/test_collect_files.py::test_collect_files_depth_2 --tb=line
        timeout: 10
        max-score: 1
    - name: Task 3
      id: task-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Task 3
        command: pytest tests/test_collect_files.py::test_collect_files_deep --tb=line
        timeout: 10
        max-score: 2
    - name: Task 4
      id: task-4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Task 4
        command: pytest tests/test_collect_files.py::test_collect_files_non_unique --tb=line
        timeout: 10
        max-score: 2
    - name: Task 5
      id: task-5
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Task 5
        command: pytest tests/test_collect_files.py::test_collect_files_max_depth --tb=line
        timeout: 10
        max-score: 3
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TASK-1_RESULTS: "${{steps.task-1.outputs.result}}"
        TASK-2_RESULTS: "${{steps.task-2.outputs.result}}"
        TASK-3_RESULTS: "${{steps.task-3.outputs.result}}"
        TASK-4_RESULTS: "${{steps.task-4.outputs.result}}"
        TASK-5_RESULTS: "${{steps.task-5.outputs.result}}"
      with:
        runners: task-1,task-2,task-3,task-4,task-5
